name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%2300E5FF
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%2300E5FF
            dist/github-snake.gif?palette=github-dark&color_snake=%2300E5FF

      - name: Copy files to writable directory
        run: |
          mkdir output
          cp dist/* output/

      - name: Change colors
        run: |
          for file in output/*.svg; do
            echo "Editing $file"

            perl -pi -e 's/#39d353/#ff3030/ig' "$file"
            perl -pi -e 's/#26a641/#bb0000/ig' "$file"
            perl -pi -e 's/#006d32/#660000/ig' "$file"
            perl -pi -e 's/#0e4429/#220000/ig' "$file"
            perl -pi -e 's/#30a14e/#ff3030/ig' "$file"
            perl -pi -e 's/#216e39/#bb0000/ig' "$file"
          done

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: output
